// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GameSave {
  id: number;
  game_id: number;
  trainer_name: string;
  trainer_id: number;
  secret_id: number;
  connected: boolean;
  save_path: string;
}
